[package]
name = "date_picker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.7"
iced_aw = "0.3"
iced_native = "0.8"
iced_graphics = "0.6.0"
chrono = "0.4.23"
